### ISSUE TITLE
Display orientation

### ISSUE THREAD

**Issue by Andy79881** [gorbachev/KiCad-SSD1306-0.91-OLED-4pin-128x32.pretty#1]
Display orientation seems to be different. According my photos the pin header is on left side. In your PCB footprint on right side. Could you clarify, which orientation is right?

Update 23.06.2024:
I have tried out with test code. Pin header has to be on left hand side. I have rotated footprint 180 degree in my Kicad library.

**Comment by Andy79881** [comment]
solved, see comment in original issue message

**Comment by KnoxE67** [comment]
would you mind sharing your symbol file with me?
